[general]
mode = viewer
decoration = yes
app_id = swayimg

[viewer]
window = #292828
transparency = grid
;scale = keep
scale = fit
antialiasing = none
history = 30
preload = 5

[gallery]
preload = yes
antialiasing = none

[list]
all = yes
fsmon = yes

[info]
show = no
info_timeout = 3
status_timeout = 3

[info.viewer]
top_left = name,imagesize,filesize,exif
top_right = none
bottom_left = index,scale
bottom_right = status,frame

[keys.viewer]
F1 = help
Left = prev_file
Right = next_file
MouseRight = next_file
bracketright = next_file
bracketleft = prev_file
Escape = exit
Home = first_file
End = last_file
Minus = zoom -20
Equal = zoom +20
ScrollUp = zoom +20 mouse
ScrollDown = zoom -20 mouse
MouseLeft = drag
f = fullscreen
j = step_down 10
k = step_up 10
h = step_left 10
l = step_right 10
n = animation
i = info
a = zoom fit
w = zoom width
p = zoom keep
