theme = "onedarker-vibrant-quiet"

#
# Editor config
#

[editor]
color-modes = true
line-number = "relative"
cursorline = true
scrolloff = 10
popup-border = "all"
rulers = [85]
bufferline = "multiple"
# helix doesn't seem to support highlight trailing space
trim-trailing-whitespace = true

[editor.auto-save]
focus-lost = true

[editor.auto-save.after-delay]
enable = true
timeout = 1000

[editor.cursor-shape]
# insert = "bar"

[editor.soft-wrap]
enable = true
wrap-indicator = "↳ "

[editor.cursor-restore]
enable = true

[editor.indent-guides]
render = true

[editor.lsp]
auto-document-highlight = true

[editor.word-completion]
trigger-length = 3

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "▷"

[editor.statusline]
left = [
    "mode",
    "spinner",
    "file-name",
    "read-only-indicator",
    "file-modification-indicator",
    "diagnostics",
]
right = [
    "file-type",
    "file-encoding",
    "position",
    "position-percentage",
]

#
# Keymaps
#

[keys.normal]
# "%" is harder to reach on keyboard
ret = "match_brackets"

# Poor man's "3C-e/y"
C-e = ["scroll_down", "scroll_down", "scroll_down"]
C-y = ["scroll_up", "scroll_up", "scroll_up"]

A-t = ":new"
A-w = ":buffer-close"
# A-h = "goto_previous_buffer"
# A-l = "goto_next_buffer"

# Macro for simulating moving lines up and down.
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select]
S-x = "extend_line_above"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select."g"]
h = "extend_to_line_start"
l = "extend_to_line_end"

[keys.insert]
A-j = "move_visual_line_down"
A-k = "move_visual_line_up"
"C-space" = "completion"

[keys.normal."space"]
"q" = ":write-quit-all"

