theme = "onedarker_vibrant"

#
# Editor config
#

[editor]
line-number = "relative"
cursorline = true
scrolloff = 10
popup-border = "all"
rulers = [85]
bufferline = "multiple"
# helix doesn't seem to support highlight trailing space
trim-trailing-whitespace = true

[editor.auto-save]
focus-lost = true

[editor.auto-save.after-delay]
enable = true
timeout = 1000

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

[editor.cursor-restore]
enable = true

[editor.indent-guides]
enable = true

[editor.lsp]
auto-document-highlight = true

[editor.word-completion]
trigger-length = 3

#
# Keymaps
#

[keys.normal]
# "%" is harder to reach on keyboard
ret = "match_brackets"
# Macro for simulating moving lines up and down.
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select]
S-x = "extend_line_above"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
A-j = "move_visual_line_down"
A-k = "move_visual_line_up"
"C-space" = "completion"

[keys.normal."space"]
"q" = ":write-quit-all"

