---
keys:
    - &me "age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6"
    - &ren "age1q0djhewgd46stjzkszzfcqallry9kd7sd6xvr94geur8ls4wz9zs6f7877"
    - &phia "age1zu5wnkx3k3dsylnft2vf5xx97wfemvaw40wyaajxhkrqy7lt2yeqwxj6xm"
    - &uk-01 "age17fq9yfjnukmdx3efel73a72gadctza7pgkz4c25n7d8vu5ye9uyqkrye0f"

creation_rules:
    - key_groups:
        - age: [ *me, *ren, *phia, *uk-01 ]
