uk-01:
    ip4: ENC[AES256_GCM,data:CItpfcER1Mkxc3apww==,iv:/0Id8fZOXd6z0suL3wbKx8jqfYXeQxEJbF/T8hSf99Q=,tag:cfMxXmYXumP32ACTKrnSYw==,type:str]
    ip6: ENC[AES256_GCM,data:WY1W57MFGODaJeBPF8v4WhLDrYw=,iv:qFxefzk2y6H+ZzkQiRLhMJ75zaK9kjZIyDGssf1sHJI=,tag:IcsYV3rs+crhmEjjVCYrsQ==,type:str]
sops:
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMWUvV1p6NzkxV3NVU2R4
            c1MxMnp4NEx3SkJXVEdCVjk1Qm90dzc1R1VzCnkrbFRFeXMySFcrOUFPLzUrZy9N
            eGF6QW51R3RjcDFqekIwOUU5SE9jck0KLS0tIG1tMW9HTUtuaTdKMUlFMXA2cHBh
            SzE4KzFyRnpxMlNMYUZLSlBQYW1MUUkKnCgP4QcU5pW7Da2Da1tkE8Pox/HwT2T/
            s1VpFgzsnBCugxa/skAeMWnDxCUQJ/mwSoRKVd2mDh51uTFJMh0eBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q0djhewgd46stjzkszzfcqallry9kd7sd6xvr94geur8ls4wz9zs6f7877
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNGFEZWRiSGt4YVI5QVo1
            dmZaNm05SXpQazgvMktFWHp2OGRnLzZMWEVnCks3a0ZiU1pjQ0toVEdBejZmVXg3
            bXR1MC9FTXMwdnNId0dKc2Y1dkhRaEUKLS0tIEhweDRtOGhCVk1jazIxckJaYkZM
            djBSTXY2eXdIT3ZBaWc1eVY1Mi8zamMKl4TE75u8nZEAlyu+h8D8CrE/EVPyR7k/
            aw1/2JgvAS4+gXqXBngtbEdqdoF0HrlzMC9K5k7a4Tdz4otYDFMHEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zu5wnkx3k3dsylnft2vf5xx97wfemvaw40wyaajxhkrqy7lt2yeqwxj6xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZU5KMWtZUXg0YTAxNkNP
            Z01naWdiSGxGakh2MkNVejlCSlRVektCNUIwCm91emxETi9BOWRjUXNhTEV2LzFN
            THRDS2JGeStnUmVMb25tSSsvWnhPL3MKLS0tIGt1VFpYQlVXbUhndmlzZEtWcDQy
            NFlSRW5hNXJjNXhieFZvYlpGUFhzVEEKtbyj/pORz47TVqL2k05J6KghQFiu3Gwl
            hZTL9I/zo5Lzns+/92gosPgriGuhM4ffxTvw3GIfu+hOpJIl5uqJAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17fq9yfjnukmdx3efel73a72gadctza7pgkz4c25n7d8vu5ye9uyqkrye0f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSmFpSEtYWm8vYUVoQU15
            N2wzaGtoS2M5aDUvUnBmZjVXdHo2WjVPS2lVClVqYzZCcGVaR3NzNTdKNXVxSWFh
            ajRVNVcyOVducVl0V2s3WWpSS1o1STgKLS0tIEFVYngxNWkvRkpkNmw1Qmo1S0dW
            Tk9GNG1FNlNaSXJvR1pBYWwyUzJpWGsKs2qf/qZfm/0Zp/aqvyZapqiigpNUvG7a
            i+STC5SLUWcBmi2snR1CxOUhF/qthOxZ6pmcE0ZJ/804X1XJH+G03Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T12:44:45Z"
    mac: ENC[AES256_GCM,data:H6RRyttTiXDo2C5rGGko2esbU/uTF3551c6rM9hmyQEaCam1eILasd4cHzg9cMQfG5kU3GT3uQXIVlT8PZOHTi1JaPOZxYSBS+qBse53WIa15FcNYbxyev4TeMJOnBoiaWGkKfT1IuM5AjqUfIAaH8Pm4mXC6j87SRBCmmXaFhU=,iv:iu7CjrpqezCgHXERMDvv/o34vdQjcdy9q0kfxqZH+XY=,tag:DluVwNYb+hudX7QuU35Fxw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
