uk-01:
    ip4: ENC[AES256_GCM,data:CItpfcER1Mkxc3apww==,iv:/0Id8fZOXd6z0suL3wbKx8jqfYXeQxEJbF/T8hSf99Q=,tag:cfMxXmYXumP32ACTKrnSYw==,type:str]
    ip6: ENC[AES256_GCM,data:WY1W57MFGODaJeBPF8v4WhLDrYw=,iv:qFxefzk2y6H+ZzkQiRLhMJ75zaK9kjZIyDGssf1sHJI=,tag:IcsYV3rs+crhmEjjVCYrsQ==,type:str]
sops:
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbHlvM251c0x5dkpxZHB6
            ODd0Q3RORXRuU3VVTWpnS2IramVGVW1LY0U0CkJrMDhwbHJWSzIzRFUrbll4dmNJ
            Y2U3L0tSZ1RkZUFySGFhOGMvaFgxazQKLS0tIEVDQ0xPMlJ6WUlCcyszb005QS9R
            bU9LMjBxTkpjT2gzcCtoM2ZrMkJyQ1EKx3g/jdHx0T+RtGSyYLsbc4BELhwt43sA
            +ADaOMDOExSQuRJdBifxAR6/CQu/M51QwWTgwN8OkuEbqfDt+Qtfng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q0djhewgd46stjzkszzfcqallry9kd7sd6xvr94geur8ls4wz9zs6f7877
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQTczUkZINExNKzk4SlhH
            dHBKUXBmN3BaeDBoZUtSYXM1eDdDSWw3Vm53CnNFYXF3enU5dlV5NXp3NWVxZXo1
            eVMwU2JkTUVFRHUxeXZFT1NnZmxrK2sKLS0tIHZIZVp0dmZrZkhzV01NQWx5MFZD
            VVJmOUYrbDEzVkJUb3R4Tjc4OGtMUWcKHhq1tSXPdtwaX2M9zqNXouYS4PnN0aOc
            +B2SsFy4hMKsKB/XVF/XRch3Ra8XV91dCEB0pmS0Wxyc5PWZfA7xqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zu5wnkx3k3dsylnft2vf5xx97wfemvaw40wyaajxhkrqy7lt2yeqwxj6xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2M1ZJSUlpYXJiRmFEVDdU
            dUY3K1gzcFhrVG80SWVkN1FnSCtEWE5iR21FCmR6cE11NjQzMHA2VTVjOXhVY3hI
            QWVaRlZ3Zzl4WW1QMnpXSGxzUlI5WU0KLS0tIDByTEhyR1hQc0w0a2ZqSzRiUDk3
            RXZ1ejVKVmZvOHNsYThzZmlmTmFuZ28KbXO8D2I1t3U86AfycKehuvxyeS5kZH/y
            iLVK+dujgfTQLtfv/JfJCFa2WVXwZsHn1f2twDsMton4o0RAtqh1DQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1068nwpttaggue0f2tstmaufl7rmvxscysg53r792862tvatdcvhs0vlmhz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQWtFcmxQN1dmMjJsTnNa
            S1hHL0d6TXRRL3ArN25aeEtldEtwSjdkeUNNCnA1c2JRdDFpZ3lLK3ZwMzFFMU0y
            Nzc1aDZCUDVscDBtb1dwbkJhVCtaTFkKLS0tIE82MGNvSU9NRUpnVjFWK0sya3lM
            dG1OdDNhbFJZaWd4UGg5eWtZUWNWVmsK0Y9F0wgNM/oNvO6NxZ6m18KceEnOgmQF
            3KYGDPLCf+wWU3QkBNLb1/LZSetK05S2PJNVt1SV9AchNWw/3dm/dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T12:44:45Z"
    mac: ENC[AES256_GCM,data:H6RRyttTiXDo2C5rGGko2esbU/uTF3551c6rM9hmyQEaCam1eILasd4cHzg9cMQfG5kU3GT3uQXIVlT8PZOHTi1JaPOZxYSBS+qBse53WIa15FcNYbxyev4TeMJOnBoiaWGkKfT1IuM5AjqUfIAaH8Pm4mXC6j87SRBCmmXaFhU=,iv:iu7CjrpqezCgHXERMDvv/o34vdQjcdy9q0kfxqZH+XY=,tag:DluVwNYb+hudX7QuU35Fxw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
