uk-01:
    ip4: ENC[AES256_GCM,data:CItpfcER1Mkxc3apww==,iv:/0Id8fZOXd6z0suL3wbKx8jqfYXeQxEJbF/T8hSf99Q=,tag:cfMxXmYXumP32ACTKrnSYw==,type:str]
    ip6: ENC[AES256_GCM,data:WY1W57MFGODaJeBPF8v4WhLDrYw=,iv:qFxefzk2y6H+ZzkQiRLhMJ75zaK9kjZIyDGssf1sHJI=,tag:IcsYV3rs+crhmEjjVCYrsQ==,type:str]
sops:
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWT1RldEMyQ0lybURwS0VJ
            SUd0LzJRYXhvUUYwczdjUG5DUGhnQ1hkYXk0CktlaW11VVBmUW5FTnNZU1JKR09x
            YWQ3ZnNaZXRPNEtMY1F1Ri8wVGVpQUUKLS0tIEhYZHM0S25YdHdlZUF3dFcyYlhl
            bHFkWUZ0TUhzUkQwakRGRnZmRWc4Q0kKaRljf5tFMZPPJUY+tYY7pzS0PFcy8FB/
            QL2IFv6g7xSvDLBwNImyq68NvPNZQsgazoj51+Sv3OFMmCR3YF7i8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q0djhewgd46stjzkszzfcqallry9kd7sd6xvr94geur8ls4wz9zs6f7877
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNm1UUExGaGROeU9zVEFy
            YXpkbE01c3F2V1RWTlAvQWdkY0draEpJODBrCnMrNUxZd3ROZCtGWE95cElkSWE1
            bllQTnhndnJndUNSZzY2R3A0WmE1NDQKLS0tIDRjNnJGQjdjWUt6MEd6SjlOVmFT
            cDJLUlpjd3NEQ2pVU0pyZEQwTE9yYjQK6MPWYtEbKYBXPyxueE9i6Wm0bLh7OUbR
            QNpL+4G5Bz/mZaH8U2ooHU5tPWMIfIcFZY7klLIYJZZUuV7sEXMVDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zu5wnkx3k3dsylnft2vf5xx97wfemvaw40wyaajxhkrqy7lt2yeqwxj6xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL2tDUjBBSjdLZTB5RDF0
            b2V6MGI2cG1jSDJsUENrYVBReHVSRW1UUG5rCmdUR2hVZDArdzV4TnZWeTNWZmZl
            QmIwZFdTQzNxMTNuSUZyODlYL3l4ZWcKLS0tIFVYTjYrRDFkbVAwRWw0OHhFUkxG
            d1A1NXFyMHhJWTdGVTIrb3hyTm5SU1kKZVdXOHoHEn3R2D/e35HTppzHziRN7JmX
            gZoqll3cA3N24d3CsOnynQG47rhPCUc4wkY3l1b9uFx6F8BkCmxdkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1068nwpttaggue0f2tstmaufl7rmvxscysg53r792862tvatdcvhs0vlmhz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVzhKQXg5VUxPVGRycTg4
            K0hxLzU4RFRGdXBTS3R6VkF4NWM0SW8vRFRBCi9tVVg1MUVLYUtOcWxTU3dFTVBi
            VVdpTmJRZDJLUGNPenVaTVRHK1h3U3MKLS0tIDNJSnA0cnNwYndzdkRoanFrdmZT
            aFo3L2V0a2xZWXlGWjVaVDVmTjViVHcKPtto+C7PxSj5FkhJyQHfKSopXxxXEZ5b
            ohhRouCE1qBiTBfQ8ZKe2nFuUygCcJdDpSip7rDFI9SObQ1vyQoObg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15zc7zreftfm8eg9ytsj3ksf9h7d8w67c2x5pfj5djlqw9z9gwe7qyv7q3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY0NSVlBYeURoc2xyVjI0
            RFE1MnJoWk9mT3lmWjdJM0x2azN3djRQbzNvClhrZm9kQzFhZWkwd25VZWw1Ukxv
            M2RLbU5QWmJOeHJvL1J1cXRaS25hOHcKLS0tIFIyTG9QQ1E2WktrOXVOcFNTVnpP
            Zmk3dm04MzNETkx3SnY2ZTRlRzh0RXMKm6FcSClRFuafDoOcgQ8qwOfV4O2xSuqr
            F5nB/f1fAB9qTDfJSMXuKh9UApuU7bhfj0TQzrevJgMkTjk2vSlpFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T12:44:45Z"
    mac: ENC[AES256_GCM,data:H6RRyttTiXDo2C5rGGko2esbU/uTF3551c6rM9hmyQEaCam1eILasd4cHzg9cMQfG5kU3GT3uQXIVlT8PZOHTi1JaPOZxYSBS+qBse53WIa15FcNYbxyev4TeMJOnBoiaWGkKfT1IuM5AjqUfIAaH8Pm4mXC6j87SRBCmmXaFhU=,iv:iu7CjrpqezCgHXERMDvv/o34vdQjcdy9q0kfxqZH+XY=,tag:DluVwNYb+hudX7QuU35Fxw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
