oauth_id: ENC[AES256_GCM,data:oWxrJR/fwVFTgM9KIOc4PX0=,iv:ObhDJ6jSFJQ5ENb7vRRX8XAAYmz2YK5y+rzcvoaUNSk=,tag:mV04IZhiYc+yM0RK0YF14A==,type:str]
oauth_secret: ENC[AES256_GCM,data:DlrXXpuMr0kinOMOYeDGzqyBkbmvW7qMgPfFLRjXD9XmWoxQbXTZQ+cLmPpWqbssri/4J1fFTRnT+Q+FIVeu1Q==,iv:AnKr9ftcGr+u0FUnn/2YpMyiKRlIcmQCcJoMRzh+VLo=,tag:o5NmJ2OpBPqqm//YW6tuOQ==,type:str]
sops:
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTXpXQ2xKZzVDbHpSSUw5
            NkdURXU4M2JMWUVuT2M3bGFDSEY4WjlxQmh3CnNtcDh3NmFLcmhjYk9xZ3kxK2xv
            WWd2K1JES3RhZVhjNVczSVg1SFdISlUKLS0tIFFEbVIybktUeVJpUnFKeFN2NHhE
            SjQ4Y1VWcUFSdTZaOTVsSWZhalBQY2sKgTLqYVaecKtUQEuSSuSQqXf0btQ88X6x
            9f2yzIoQf9yCAb5hSUMHCdEerfT8Uj+DfZ8Uv/fw+fO8B8q4fr2L/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q0djhewgd46stjzkszzfcqallry9kd7sd6xvr94geur8ls4wz9zs6f7877
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEekl1SU9KS0M0WXJqZ3Jj
            ODYzK3NOaW1TWDlUdXRYUDkrU0lFclVGZXk0ClZlNC9JaUhkQ0d1eFdsR3dsYzNH
            NUhPZ1BpYTdYNlIyZWU5U0xQbE1hZ1UKLS0tIEVqalo1TDJ0SlhlWGxaZk5mZFF0
            YVZvRStnSEd1bGxjYTdMNnROcmNRUFkKmu++45KlemHGGYS/W/7WmoF3HRMHaPwQ
            rZzBQYmMlFvkI1mZGUlgxvXcE30hrJSh6nXKIY3wlXepLgXhYbQPLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zu5wnkx3k3dsylnft2vf5xx97wfemvaw40wyaajxhkrqy7lt2yeqwxj6xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWTBkclFRbHFwejAvU3lN
            RG1ERXBDeFFQVU9ONjlJTW13WmZHRmNFSUNjCnlYUGZGZW9HZ1llWmdQblZmdUlB
            bjNCSWROU2ZkRGF6c2NWUmd2cXYzOVEKLS0tIDRHNUxyMEZEU1BMbjZETHIvZlpR
            SU1GamE2eGMrL0ZXVkhXL3BKS2JScFkK7i2wcU6iTew49kYn5h4PZJZLI8cA4zfl
            nyRAph+Xb7I89QFn1xL7kmEFU+ceKuLuEOhZcSd+5o7+5XaQyTke/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1068nwpttaggue0f2tstmaufl7rmvxscysg53r792862tvatdcvhs0vlmhz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwenU4emd0VXN6TStYWjho
            bDRkZC90WGpzVHhaZE5ZeHRYbEZqRnJLUVc0Clh6Z3JOYXZtc3JOODgxcUNLSHRR
            MTUwS2xOQ3kzancxNlM4RllzV3duWXcKLS0tIEkxQjVWc3JSVUtSYUxtQlJZTmk4
            djBUTVZKSHRWNXBLY1BicVQ4eDF1OE0Ke7hyaOSj82j52olG/7KVBsHgH3VAhJ0V
            YjsvTHhnCaWuuPc3D2QhZ6N4mFfM7M47LFs5FPvrOwLTK3IVLIYDjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-31T15:11:35Z"
    mac: ENC[AES256_GCM,data:m3uyZN6JhRH99BBB7SqVcDbe3hf23t6B0CxAcDYWFYGfGv3NmqlMH+XmPQPVPVeLrQCsBB2HbGTUspV2KcsrkIBJ+pB7otddqQBO3Fi6ZCQel30i++Jrb51Xsedb00ImV4LYF2Zg2Da7bm1t7f+dSzKloYNM1jK/9N6Cq0xr+IA=,iv:0PKLqQOhSwPnncD6DpLxAFdmkkick1wVGeSpCyYErs0=,tag:ezLT+iev5D6mlHK7Xx7NOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
