oauth_id: ENC[AES256_GCM,data:oWxrJR/fwVFTgM9KIOc4PX0=,iv:ObhDJ6jSFJQ5ENb7vRRX8XAAYmz2YK5y+rzcvoaUNSk=,tag:mV04IZhiYc+yM0RK0YF14A==,type:str]
oauth_secret: ENC[AES256_GCM,data:DlrXXpuMr0kinOMOYeDGzqyBkbmvW7qMgPfFLRjXD9XmWoxQbXTZQ+cLmPpWqbssri/4J1fFTRnT+Q+FIVeu1Q==,iv:AnKr9ftcGr+u0FUnn/2YpMyiKRlIcmQCcJoMRzh+VLo=,tag:o5NmJ2OpBPqqm//YW6tuOQ==,type:str]
sops:
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN0Rtd1E4Q1RuRkc4a2th
            QmIrcTF5V1JCS3Ewa28yNkp6UUtEckR6RVJ3CjA4T3YvZ0xsS2l3WTh5QU5VRTlW
            akpiekJNbFJFRE1xLzFod1M3U2lzdEkKLS0tIE9uVTA0M2dnNS9HRG84MFNWZ21r
            QWNOUkE0N3hSNGJQekJ3aVBZQTNOcTAK4rI0SoR5cgmk4bpdax3kPrY9/Cj59WES
            i/83IImeD7FHEt3hWBDDHGi5DCqQmiiAtrKnRi4sWOFeQw4biscF1A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q0djhewgd46stjzkszzfcqallry9kd7sd6xvr94geur8ls4wz9zs6f7877
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSVFJNlVWZjUyTFo0Ni8z
            OFlvYjZTTnFvam9SYTFiTmtXUVJzQkE3TzI0CmluZjlKZHc4YVh6a0NmWm51RHls
            U0hTd2JXSjQwWmZ2UGphMUZ2QjFuMHcKLS0tIHJHK0xjY041aXFZWHRybldrVFRk
            d0MrRW92RHNLdnJaL00wUUJFRDBZVWsKnVyiCrJHmFGi/Dy3Ck3woLQPmL/85PXS
            UPaksZID4iccHh6SkhOLKqGXZf8Mf5k+i1TnXgiM2MeQbdb81r8GvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zu5wnkx3k3dsylnft2vf5xx97wfemvaw40wyaajxhkrqy7lt2yeqwxj6xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUFNFVTVwQW82Ris4TE1z
            SUNpQnZwSzVXM3pLQTZGU2t1a0wyWjFnOEdJCkc0QzRrWDJ6UDdJdmFWM1RBcVpv
            SUJ2UExCY1J5NDRmb2ZhZUIzZmVub0EKLS0tIEVYVFUwblNYYTU3dlpyQ2EvNThr
            S3RsOEFEb041UWhwUkRzWVhzcVZ6dnMKjTDwf2db8iRqgDej+KpbyMqY4kKRK1XP
            MuWKTetXEmzgCsp5GF3t7Xr9YdT9+e8sV1Os/uLCCOotdtl4PQlvDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17fq9yfjnukmdx3efel73a72gadctza7pgkz4c25n7d8vu5ye9uyqkrye0f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZkV3anlHMlZIVlVBU1ZZ
            enphT3Vub2p5RVpFdTVZbDc5Q2plT2tqV3dRCjNkeTBoNFB6MzhLSUFPU1g1bW91
            eXh3MndwSDBGY1A1Skt2ME1pNkd0dFkKLS0tIDhQRThnRGFPa3BEOGk3VG9ha3E1
            SGRmWTJpMzZSYnpuSXFWVWhjVURpdU0K6fYX1bSP7sNTGBI25/gWGta6xQAUsOs7
            M2DghaMEHNzdIQp2AxlKl8qt6Xl0+5KOXtKgIJVNQmQ3SH8badDlBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-31T15:11:35Z"
    mac: ENC[AES256_GCM,data:m3uyZN6JhRH99BBB7SqVcDbe3hf23t6B0CxAcDYWFYGfGv3NmqlMH+XmPQPVPVeLrQCsBB2HbGTUspV2KcsrkIBJ+pB7otddqQBO3Fi6ZCQel30i++Jrb51Xsedb00ImV4LYF2Zg2Da7bm1t7f+dSzKloYNM1jK/9N6Cq0xr+IA=,iv:0PKLqQOhSwPnncD6DpLxAFdmkkick1wVGeSpCyYErs0=,tag:ezLT+iev5D6mlHK7Xx7NOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
