oauth_id: ENC[AES256_GCM,data:oWxrJR/fwVFTgM9KIOc4PX0=,iv:ObhDJ6jSFJQ5ENb7vRRX8XAAYmz2YK5y+rzcvoaUNSk=,tag:mV04IZhiYc+yM0RK0YF14A==,type:str]
oauth_secret: ENC[AES256_GCM,data:DlrXXpuMr0kinOMOYeDGzqyBkbmvW7qMgPfFLRjXD9XmWoxQbXTZQ+cLmPpWqbssri/4J1fFTRnT+Q+FIVeu1Q==,iv:AnKr9ftcGr+u0FUnn/2YpMyiKRlIcmQCcJoMRzh+VLo=,tag:o5NmJ2OpBPqqm//YW6tuOQ==,type:str]
sops:
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM0dJeTIxZnd5YWpNaVNz
            YmlsT3FpVVArbFQvWXdUeTdLTVdOdFMybW5vCkM1MlVlWWV3VFNjWEJiNTg0QnNV
            Smx3MHM4K2pjcWZtQ0JtdzVaYUp0WUEKLS0tIG5VVkxucFE0R2NWNmZEanpGWlg2
            d0FURDJBY0hVVGRtUVg1N1c2M0dHQ2sKGiygAKzEuKaJhj7NRLNeZZcoMEDUs4D6
            VZLv5xG6cmXWfpWB/77QbJlKIZBPS/AqzB8zn5mzlE3c357KeXf5/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q0djhewgd46stjzkszzfcqallry9kd7sd6xvr94geur8ls4wz9zs6f7877
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleFZCVG14UmtpWUxqSW9D
            NkVRRkM0NGdMR0JqbVRBSXVybTNEdjZ0c1Z3Ck01RHRTdTRIM3doMXZPMmNDTExG
            bmhLMWYxMVQzcXRpZVFzd0pqU2p4WHcKLS0tIFo3Rk43ekpRZGdyMmxrSHR6ZUwr
            WVpLUHdqN3JtSHpmTlExQnRHUlVnYTgKT1qcoiADyrcNg/BThQmisEiwTCLQpDSo
            OKWPy9kEERIGuV9DD88EuSztn5/QLf2FfCiX5a3l6/KBdwJ3BjaXgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zu5wnkx3k3dsylnft2vf5xx97wfemvaw40wyaajxhkrqy7lt2yeqwxj6xm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUVh1QkJsYjhGT3BsRGdn
            dDNWaTZmRjFpT3hoTW4rcnJBZW5EYjZtd21RCmErMVZqZVNTVW9jeE4rR3cyWUps
            R0lPNXdQRjlwQmpoa09tLzNnU3pnYUUKLS0tIDNWVHErcTFuSi81a2o3TXNxampG
            VTdPTjB1ZzFzbWdLSGl6QUVFSGh3THMKiOvp/S87zZoYs1Iyt2s+PIYoVkKDwtUg
            MjePLgWnUNG34jMLARGWLBErrOBBRsGQIRg/I4UaEB3L4oaQcAMUyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1068nwpttaggue0f2tstmaufl7rmvxscysg53r792862tvatdcvhs0vlmhz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxV2VZcHhOU2FwY1lSeUhR
            ZVc4NkZmbHdyYVQ2dnVlSHRYbUdUOUVtV0djCnJ1RHhzdytNR0FwVUkrL3YyNGsx
            WlpCS3FRbXBDOWdPbzFaWEwrd1F2SXMKLS0tIFE4K01ZNDd5R2x3ZFlyUGVBM2RG
            eklvaXV3dTJlbzliaVRZOVNscHg1cU0KspSYpoh4qjPYsGdP9jUuRvfqswTnT27j
            3wmMN9THSs9WjwHUVWtlBgI79kzNoXzToXv1o+0viGf+n1kc0SBfHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-31T15:11:35Z"
    mac: ENC[AES256_GCM,data:m3uyZN6JhRH99BBB7SqVcDbe3hf23t6B0CxAcDYWFYGfGv3NmqlMH+XmPQPVPVeLrQCsBB2HbGTUspV2KcsrkIBJ+pB7otddqQBO3Fi6ZCQel30i++Jrb51Xsedb00ImV4LYF2Zg2Da7bm1t7f+dSzKloYNM1jK/9N6Cq0xr+IA=,iv:0PKLqQOhSwPnncD6DpLxAFdmkkick1wVGeSpCyYErs0=,tag:ezLT+iev5D6mlHK7Xx7NOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
