hwdec=auto
vo=gpu-next
hwdec=vaapi
gpu-context=wayland
hdr-compute-peak=no
cache=yes

deband=no

window-maximized=yes
save-position-on-quit=yes
hr-seek = yes
force-seekable=yes

volume=90
replaygain=album

include = ~~/profile-image-viewer.conf
