hwdec=auto
vo=gpu-next
hwdec=vaapi
gpu-context=wayland
hdr-compute-peak=no
cache=yes
priority=high

deband=no

window-maximized=yes
save-position-on-quit=yes
force-seekable=yes

volume=90
replaygain=album

[image-viewer]
