[package]
name = "localbinbox"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
anyhow = "1.0.100"
ino_color = "3.0.0"
itertools = "0.14.0"
tap = "1.0.1"

[lints.clippy]
all = { priority = -1, level = "warn" }
pedantic = { priority = -1, level = "warn" }
nursery = { priority = -1, level = "warn" }
