[package]
name = "localbinbox"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
gix-discover = "0.43.0"
ignore = "0.4.25"
ino_color = "4.0.0"
ino_iter = "0.1.0"
ino_tracing = "0.1.1"
itertools = "0.14.0"
saphyr = "0.0.6"
tap = "1.0.1"
tracing = "0.1.43"

[lints.clippy]
all = { priority = -1, level = "warn" }
pedantic = { priority = -1, level = "warn" }
nursery = { priority = -1, level = "warn" }
