name: Some Nix Things

inputs:
    cachix_token: { required: true }

runs:
    using: composite

    steps:
        - name: Mount swap
          shell: bash
          run: |
              {
                F="/mnt/swapf"
                sudo swapoff --all
                sudo dd if=/dev/zero of=$F bs=1M count=20480
                sudo chmod 600 $F
                sudo mkswap $F
                sudo swapon $F
              } &
              disown

        - name: Move TMPDIR
          shell: bash
          run: |
              sudo sh -c 'uuidgen > /mnt/touchit' &
              builddir="/mnt/$(uuidgen)"
              sudo mkdir -p "$builddir"
              sudo chmod 1777 "${builddir}"
              echo "TMPDIR=${builddir}" >> $GITHUB_ENV
              echo "TMPDIR set to ${builddir}"

        - name: Setup nix
          uses: MidAutumnMoon/spheti-action/nix@master
          with:
              cachix-url: "https://nuirrce.cachix.org/"
              cachix-pubkey: "nuirrce.cachix.org-1:KQWa6ZfDkMPXeDiUpmyDhNw4CmgybPyeVklmi/1Rtqk="

        - name: Setup cachix
          uses: cachix/cachix-action@v16
          with:
              installCommand: "nix profile install .#cachix"
              name: "nuirrce"
              pushFilter: '(NVIDIA.*\.run)'
              skipAddingSubstituter: true
              authToken: ${{ inputs.cachix_token }}
# vim: nowrap:
