name: Some Nix Things

inputs:
    cachix_token: { required: true }
    update_flake: { required: false, default: true }

runs:
    using: composite

    steps:

    -   uses: wimpysworld/nothing-but-nix@main

    -   name: Setup nix
        uses: MidAutumnMoon/spheti-action/nix@master
        with:
            cachix-url: "https://nuirrce.cachix.org/"
            cachix-pubkey: "nuirrce.cachix.org-1:KQWa6ZfDkMPXeDiUpmyDhNw4CmgybPyeVklmi/1Rtqk="

    -   name: Update flake
        if: ${{ inputs.update_flake }}
        shell: bash
        run: |
            nix flake update

    -   name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
            installCommand: "nix profile install .#cachix"
            name: "nuirrce"
            pushFilter: '(NVIDIA.*\.run)'
            skipAddingSubstituter: true
            authToken: ${{ inputs.cachix_token }}

# vim: nowrap:
