#!/usr/bin/env ruby

# frozen_string_literal: true

require "pathname"
require "shellwords"

BACKUP_DIR = Pathname.pwd.join ".backup"

# TODO: coordinate rename original to .backup
abort "Leaftover backup folder found" \
    if not Pathname.pwd.glob("./**/original").empty?

abort %("#{BACKUP_DIR}" exists) \
    if BACKUP_DIR.exist?

BACKUP_DIR.mkdir

warn %(BACKUP_DIR is "#{BACKUP_DIR}")

if ARGV.empty?
    warn "Glob pwd for directories to be archived"
    warn "However files are ignored"
    INPUTS = Pathname.pwd
        .glob("*")
        .select(&:directory?)
else
    INPUTS = ARGV
        .map { Pathname.new it }
        .map(&:realpath)
        .tap do
            abort "All arguments must be directory" \
                unless it.all?(&:directory?)
        end
end

INPUTS.each do |input|

    puts %(Archiving "#{input.basename}")

    archive_name = Pathname.new "#{input}.7z"

    # lzma2 compression
    # ultra
    # solid block 16GB
    # dictionary 3840MB
    # large pages
    system <<~SH or abort "Failed to run 7z"
        command 7zz a \
            -slp -ssp \
            -sas -t7z \
            -m0=lzma2 \
            -mx9 -myx9 \
            -ms=16G \
            -md=3840M \
            -- \
            #{archive_name.to_s.shellescape} \
            #{input.to_s.shellescape}
    SH

    warn "Move to backup"

    BACKUP_DIR.join(input.basename)
        .then { input.rename it }

    warn "Generate parchive"

    system <<~SH or abort "Failed to par"
        ,par #{archive_name.to_s.shellescape}
    SH

end
