#!/usr/bin/env ruby

# frozen_string_literal: true

require "pathname"
require "shellwords"

TOPLEVEL = (ARGV.shift or abort "Not argument")
    .then { Pathname.new it }
    .then(&:realpath)

BACKUP_DIR = (TOPLEVEL.join ".backup")
    .tap do |dir|
        dir.exist? and abort "Backup dir exists"
        dir.mkpath
    end

TOPLEVEL.glob("*.jpg").each do |pic|
    puts "Process #{pic}"

    out = pic.sub_ext(".png")
    backup = pic.basename.then { BACKUP_DIR.join it }

    system <<~SH or abort "Failed to run magick"
        magick -verbose \
            #{pic.to_s.shellescape} \
            -colorspace Gray \
            -strip \
            -unsharp 0x2+1+0.4 \
            -threshold 55% \
            -background black -alpha remove \
            -depth 1 -colors 2 \
            -define png:compression-level=1 \
            #{out.to_s.shellescape}
    SH

    pic.rename(backup)
end
