[main]
term = xterm-256color
font = monospace:size=13.5
dpi-aware = yes
initial-window-mode = maximized
; shell = fish

[scrollback]
lines = 10000

[key-bindings]
font-increase = none
font-decrease = none
