[main]
# term = xterm-256color
# font = Monaspace Argon NF:size=13.5
font = Maple Mono NL NF CN:size=13
dpi-aware = yes
box-drawings-uses-font-glyphs = true

[url]
osc8-underline = always
style = curly

[scrollback]
lines = 10000

[key-bindings]
font-increase = none
font-decrease = none
show-urls-copy = Control+Shift+y

[colors-dark]
alpha = 0.8
alpha-mode = all
blur = true

