//! Runtime configuration.
//!
//! psd reads a JSON config file generated by the NixOS module. We
//! deliberately avoid the shell-style `psd.conf` so types are explicit
//! and validation is upfront.

use std::path::Path;
use std::path::PathBuf;

use anyhow::Context;
use anyhow::Result;
use serde::Deserialize;

use crate::apps::AppKind;

#[derive(Debug, Deserialize)]
pub struct Config {
    /// Apps to manage. Must be non-empty.
    pub apps: Vec<AppKind>,
}

impl Config {
    /// Load from a JSON file.
    pub fn load(path: &Path) -> Result<Self> {
        let raw = std::fs::read_to_string(path).with_context(|| {
            format!("reading config {}", path.display())
        })?;
        let cfg: Self = serde_json::from_str(&raw).with_context(|| {
            format!("parsing config {}", path.display())
        })?;
        if cfg.apps.is_empty() {
            anyhow::bail!("config: `apps` must not be empty");
        }
        Ok(cfg)
    }

    /// Default config path: `$XDG_CONFIG_HOME/psd/config.json`,
    /// falling back to `~/.config/psd/config.json`.
    pub fn default_path() -> Result<PathBuf> {
        if let Ok(p) = std::env::var("XDG_CONFIG_HOME") {
            return Ok(PathBuf::from(p).join("psd/config.json"));
        }
        let home = std::env::var("HOME").context("HOME is not set")?;
        Ok(PathBuf::from(home).join(".config/psd/config.json"))
    }
}
