name: "Build Packages & NixOS"

on:
    workflow_dispatch:
    push:
        paths:
            - "flake.*"
            - "packages/**"
            - "machine/**"
            - "nixos/**"
    schedule:
        #- cron: "0 */4 * * *"
        - cron: "0 0 */2 * *"

env:
    CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

jobs:
    list_groups:
        name: List package groups
        runs-on: ubuntu-latest
        defaults:
            run: { shell: bash }
        outputs:
            groups: ${{ steps.list_groups_step.outputs.groups }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup nix
              uses: ./.github/actions/nix-pieces
              with:
                  cachix_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

            - name: Get subjects
              id: list_groups_step
              run: |
                  TOOL=".#tsuki.__maintenance"
                  nix build --print-build-logs "$TOOL"
                  OUT=$( nix run "$TOOL" \
                      -- build -m "packages/tsuki.nix" -l )
                  echo "groups=${OUT}" >> "$GITHUB_OUTPUT"

    build_packages:
        name: Build Packages
        runs-on: ubuntu-latest
        defaults:
            run: { shell: bash }
        needs:
            - list_groups
        strategy:
            matrix:
                group: ${{ fromJSON(needs.list_groups.outputs.groups) }}
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup nix
              uses: ./.github/actions/nix-pieces
              with: { cachix_token: "${{ secrets.CACHIX_AUTH_TOKEN }}" }

            - name: Build Packages from Group
              run: |
                  TOOL=".#tsuki.__maintenance"
                  nix flake update
                  nix run "$TOOL" -- build \
                      -m "packages/tsuki.nix" \
                      -g "${{ matrix.group }}"

    # build-nixos:
    #     name: Build NixOS
    #     needs:
    #         - build_packages
    #     runs-on: ubuntu-latest
    #     defaults:
    #         run: { shell: bash }
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v5

    #         - name: Setup nix
    #           uses: ./.github/actions/nix-pieces
    #           with: { cachix_token: "${{ secrets.CACHIX_AUTH_TOKEN }}" }

    #         - name: Build NixOS
    #           run: |
    #               nix run --print-build-logs \
    #                   .#tsuki.__tools.build-driver -- nixos

# vim: nowrap:
