name: "Build Packages & NixOS"

on:
    workflow_dispatch:
    push:
        paths:
        - 'flake.*'
        - 'packages/**'
        - "machine/**"
        - "nixos/**"
    schedule:
        #- cron: "0 */4 * * *"
        - cron: "0 0 */2 * *"

env:
    CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

jobs:

    all_subjects:
        name: Get Subjects to Build
        runs-on: ubuntu-latest
        defaults:
            run: { shell: bash }
        outputs:
            subjects: ${{ steps.get_subjects.outputs.subjects }}
        steps:
        -   name: Checkout
            uses: actions/checkout@v5

        -   name: Setup nix
            uses: ./.github/actions/nix-pieces
            with:
                cachix_token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
                update_flake: false

        -   name: Get subjects
            id: get_subjects
            run: |
                nix build --print-build-logs ".#tsuki.__tools.build-driver"
                out=$( nix run ".#tsuki.__tools.build-driver" \
                    -- subjects "packages/manifest.rb" )
                echo "subjects=${out}" >> "$GITHUB_OUTPUT"

        # -   name: Setup tmate session
        #     #if: ${{ failure() }}
        #     uses: mxschmitt/action-tmate@v3


    build_packages:
        name: Build Packages
        runs-on: ubuntu-latest
        defaults:
            run: { shell: bash }
        needs:
            - all_subjects
        strategy:
            matrix:
                subject: ${{ fromJSON( needs.all_subjects.outputs.subjects ) }}
            fail-fast: false
        steps:
        -   name: Checkout
            uses: actions/checkout@v5

        -   name: Setup nix
            uses: ./.github/actions/nix-pieces
            with: { cachix_token: '${{ secrets.CACHIX_AUTH_TOKEN }}' }

        -   name: Build Subject
            run: |
                nix run --print-build-logs \
                    .#tsuki.__tools.build-driver -- build \
                    "packages/manifest.rb" "${{ matrix.subject }}"

    build-nixos:
        name: Build NixOS
        needs:
            - build_packages
        runs-on: ubuntu-latest
        defaults:
            run: { shell: bash }
        steps:
        -   name: Checkout
            uses: actions/checkout@v5

        -   name: Add swap
            uses: pierotofy/set-swap-space@master
            with: { swap-size-gb: "20" }

        -   name: Setup nix
            uses: ./.github/actions/nix-pieces
            with: { cachix_token: '${{ secrets.CACHIX_AUTH_TOKEN }}' }

        # -   name: Free up disk
        #     env:
        #         ACTION_DEBUG_OUTPUT: ${{ runner.debug }}
        #     run: |
        #         nix run .#fish -- \
        #             -PN "$GITHUB_WORKSPACE/packages/__tools/cleansing.fish" "light"

        -   name: Build NixOS
            run: |
                nix run --print-build-logs \
                    .#tsuki.__tools.build-driver -- nixos

# vim: nowrap:
